CREATE FUNCTION getNthHighestSalary(N INT) RETURNS INT
BEGIN
  RETURN ( SELECT DISTINCT SALARY FROM
      
     (SELECT SALARY , DENSE_RANK() OVER(ORDER BY SALARY DESC)AS SALARY_RANK FROM EMPLOYEE)T
          WHERE T.SALARY_RANK = N LIMIT 1 
      
  );
END